name: Standard issue
description: Feature, bug or hotfix
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Feature
        - Bug
        - Hotfix
  - type: textarea
    id: description
    attributes:
      label: Description
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
