name: 'Lint Backend et Frontend'

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            saintBarthVolleyApp/backend/package-lock.json
            saintBarthVolleyApp/frontend/package-lock.json

      - name: 'Installer les dépendances backend'
        run: npm ci
        working-directory: saintBarthVolleyApp/backend

      - name: 'Lancer ESLint backend'
        run: npx eslint . --ext .js,.ts
        working-directory: saintBarthVolleyApp/backend

      - name: 'Installer les dépendances frontend'
        run: npm ci
        working-directory: saintBarthVolleyApp/frontend

      - name: 'Lancer ESLint frontend'
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
        working-directory: saintBarthVolleyApp/frontend

      - name: 'Prettier check (global)'
        run: npx prettier --check "saintBarthVolleyApp/**/*.{js,ts,tsx,jsx,json}" --ignore-path .gitignore
